# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Use different gapsout for different setup
source = ~/.config/hypr/looknfeel.local.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

# use whatever shortcut floats your boat
bind = Alt, Space, exec, vicinae toggle

# old rule syntax (Hyprland < 0.53)
# blur
# layerrule = blur, vicinae
# layerrule = ignorealpha 0, vicinae
# disable animation for vicinae only
# layerrule = noanim, vicinae

# blur
layerrule {
    name = vicinae-blur
    blur = on
    match:namespace = vicinae
}

# disable animation for vicinae only
layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}

misc {
    focus_on_activate = true
}

windowrule {
  name = windowrule-1
  opacity = 0.7
  match:class = (vicinae)
}


# HyprMod managed settings
source = /home/adib/.config/hypr/hyprland-gui.conf
